### PR TITLE
Add --no-color flag (#21)

### LINKED ISSUE #21: Add --no-color flag
Add `--no-color` flag by default like `--quiet` flag.

### PR DESCRIPTION
**Pull request by DDtKey**
Must be merged after release [dotenv-linter v3.0.0](https://github.com/dotenv-linter/dotenv-linter/issues/334) :slightly_smiling_face: 
Closes #21

### CODE REVIEW

**Review by mgrachev — DISMISSED** [review]
@DDtKey Thank you for your help! 👍

**Comment by mgrachev** [comment]
@DDtKey Please resolve the merge conflict 🙏

**Review by mgrachev — APPROVED** [review]

**Comment by DDtKey** [comment]
It looks like now there is an error with passing arguments in the master branch 🤔 

This was the cause of the merge conflict.

**Comment by mgrachev** [comment]
> It looks like now there is an error with passing arguments in the master branch 🤔
> 
> This was the cause of the merge conflict.

Yes, we will fix this error in the release v3.0.0.

**Pull request merged**
